name: Job Output
on:
  push:
    branches:
      - master
  jobs:
    first-job:
      outputs:
        app_version: ${{ steps.publish_version.outputs.version-no }}

      runs-on: ubuntu-latest
      steps:
        - name: Publish the version
          id: publish_version
          run: echo "version-no=3" >> $GITHUB_OUTPUT

    second-job:
      runs-on: ubuntu-latest
      needs: first-job
      steps:
        - name: Get the output
          run: echo "Version of the app is ${{ needs.first-job.outputs.app_version }}"
        - name: Print Output Success
          run: echo "Output fetch successfull"
